### ISSUE TITLE
is it possible to make sentiment analysis with Indonesian languange?

### ISSUE THREAD

**Issue by hendrarespati** [kunaldhariwal/TwisentR#1]
hi kunaldhariwal,
i've tried your apps and its work amazing.
i want to ask question, is there any package recommendation for indonesia languange? i want to build sentiment analysis about movi sentimen analysis using your dashboard

**Comment by kunaldhariwal** [comment]
@hendrarespati You can use my dashboard, no issues.
Sorry, i don't think there's any package available for that.
And thank you :+1:

**Comment by kunaldhariwal** [comment]
Although, You can check this out. It's for NLP though.
https://www.r-bloggers.com/natural-language-processing-for-non-english-languages-with-udpipe/
